"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[git]
private-commits = "description(glob:'wip:*')"
subprocess = true
sign-on-push = true
push-new-bookmarks = true

[aliases]
gcl = ["git", "clone", "--colocate"]
gp = ["git", "push"]
gpc = ["git", "push", "--change"]
gpr = ["git", "push", "--revisions"]
gf = ["git", "fetch"]
gfu = ["git", "fetch", "--remote", "upstream"]
gfa = ["git", "fetch", "--all-remotes"]
up = ["rebase", "--skip-emptied", "--source", "all:roots(trunk()..@)", "--destination", "trunk()"]
wc = ["edit", "working-copy"]
de = ["diffedit"]

tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
[revsets]
log = "trunk()..@" 

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[user]
name = "pylbrecht"
email = "pylbrecht@mailbox.org"

[core]
fsmonitor = "watchman"

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

[fsmonitor]
backend = "watchman"

[fsmonitor.watchman]
register-snapshot-trigger = true
