[git]
private-commits = "description(glob:'wip:*')"

[aliases]
l = ["log"]
lb = ["log", "-r", "((bookmarks() & mine()) ~ ::trunk())::"]
gp = ["git", "push"]
gf = ["git", "fetch"]
gfa = ["git", "fetch", "--all-remotes"]

[revsets]
log = "trunk()..@" 

[ui]
default-command = "log"

[user]
name = "pylbrecht"
email = "pylbrecht@mailbox.org"
