[git]
private-commits = "description(glob:'wip:*')"

[aliases]
l = ["log"]
gp = ["git", "push"]
gf = ["git", "fetch"]
gfa = ["git", "fetch", "--all-remotes"]
up = ["rebase", "--skip-emptied", "--source", "all:roots(trunk()..@)", "--destination", "main"]

[revsets]
log = "trunk()..@" 

[ui]
default-command = "log"
diff.format = "git"

[user]
name = "pylbrecht"
email = "pylbrecht@mailbox.org"
