alias sc-enable="sudo systemctl enable"
alias sc-disable="sudo systemctl disable"
alias sc-start="sudo systemctl start"
alias sc-stop="sudo systemctl stop"
alias sc-restart="sudo systemctl restart"
alias sc-status="systemctl status"

alias scu-enable="systemctl --user enable"
alias scu-disable="systemctl --user disable"
alias scu-start="systemctl --user start"
alias scu-stop="systemctl --user stop"
alias scu-restart="systemctl --user restart"
alias scu-status="systemctl --user status"
